title: Jotone's Blog
language: en
url: "https://jotone.it"

tagline: "John's Personal Blog"
description: "John's Personal Blog. I write mainly about my projects."
keywords: "development, personal, projects, blog"

author: 
  name: John Toniutti
  url: "https://jotone.it/about"
  image: "/assets/images/about.webp"

copyright: "Copyright (c) 2024 John Toniutti"

email: "john.toniutti@gmail.com"
github_url: https://github.com/jotonedev
linkedin_url: https://www.linkedin.com/in/john-toniutti/
telegram_url: https://t.me/joto34

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/default.webp"
      permalink: :path/:title
      seo:
        type: BlogPosting

# Analytics
cloudflare: "aa3b155a9c5b4f08b2aa4e6e69f7a76a"

# Plugin settings
seo:
  type: BlogPosting
social: 
  name: John Toniutti
  links:
    - https://github.com/jotonedev
    - https://www.linkedin.com/in/john-toniutti/

feed:
  posts_limit: 20
  excerpt_only: true
  disable_in_development: true

sass:
  style: compressed
  sass_dir: _sass

sitemap: true

# Build settings
theme: jekyll-theme-tallneck
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
