baseURL                = "https://jotone.it/"
languageCode           = "en-us"
defaultContentLanguage = "en"
title                  = "Jotone's blog"
copyright              = "John Toniutti"
enableRobotsTXT        = true

[taxonomies]

[minify]
  minifyOutput = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"

  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "assets/company"
    target = "static/company"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "images"
    target = "static/images"

  [[module.mounts]]
    source = "images"
    target = "assets/images"

  [[module.mounts]]
    source = "photos"
    target = "assets/photos"

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "monthly"
  filename   = "sitemap.xml"
  priority   = 0.5

[imaging]
  quality        = 85
  resampleFilter = "Lanczos"
  bgColor = "#ffffff"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses = true
    noHl      = false
    style     = 'rrt'
    tabWidth  = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  author = "John Toniutti"
  description = "Personal blog of John Toniutti"
  keywords    = ["John Toniutti", "jotone", "jotonedev"]
  email       = "contact@jotone.it"
  socialCard = "social-card.jpg"
  themeColor = "#4f46e5"

  [params.theme_config]
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true
